### ISSUE TITLE
Remove Git History

### ISSUE THREAD

**Issue by duichwer** [kine/navertical#15]
I like your extension to setup new projects, but I would prefer it to remove automatically the `.git` history of the template project before pushing the repository back to the new repo.
Maybe this could be a setting which has to be enabled?

**Comment by kine** [comment]
Hi @duichwer ,
All depends on how you are using this. E.g. I am having the history because I want to be able to update the app later when I e.g. change something in the template (for example fix something, update it to be compatible with new version of BC etc.) and I want to be able to merge these changes to all apps created from this template. Thus I need the history, because I want to be able to use git merge functioality for this. Without the history, this cannot be done. 

If you want to not "clone" the repository, but rather just copy the files from there and have "detached" app (no relation to the template), it could be added. But do you really want to lost this possibility to update the app from new template version?

**Comment by kine** [comment]
Published in v0.5.2
